Added Nate greeting
UMM-CSci-3601-S24/intro-to-git-everyone pull request #13
Opened 2024-01-18 20:13 UTC by NateFerrell

2024-01-20 23:05 UTC, NicMcPhee requested changes

2024-01-20 23:05 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
>    }
You're missing the closing brace after your greeting, which is why this won't compile and run.

```suggestion
  private String nateSaysHello() {
    return "Nate says 'Hola!'\n";
  }
  
  private String kkSaysHello() {
    return "KK says 'Hello!'\n";
  }
```

2024-01-22 21:16 UTC, NicMcPhee approved these changes

2024-01-22 21:49 UTC, AndreasNelson approved these changes
looks alphabetical to me

2024-01-22 21:50 UTC, merged