Greetings from alija
UMM-CSci-3601-S24/intro-to-git-everyone pull request #20
Opened 2024-01-20 23:41 UTC by alijawosti

hopefully fixing build failures

2024-01-20 23:44 UTC, LinneaMay reviewed
looks good!

2024-01-20 23:45 UTC, LinneaMay submitted a review, later dismissed
looks good

2024-01-21 15:29 UTC, NicMcPhee requested changes
As mentionted above, you've removed (thrown away) a bunch of other people's greetings, which is totally not cool.

You have to fix that before you can merge this in, and no one should approve this PR without confirming that these have been restored.

2024-01-21 15:29 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> -    builder.append(jadenSaysHello());
This is very definitely a Bad Thing. You appear to have removed _many_ of the other people's greetings, probably while handling merge conflicts. You definitely removed all three of these, and it looks like you removed Ken, Pat, and Tristan below.

You have to fix that before you can merge this in, and no one should approve this PR without confirming that these have been restored.

2024-01-22 20:26 UTC, closed without merging