Add greeting from Malena
UMM-CSci-3601-S24/intro-to-git-everyone pull request #7
Opened 2024-01-18 20:13 UTC by mahon479

I added Malena's greeting.

2024-01-18 20:20 UTC, NicMcPhee submitted a review, later dismissed
This looks great - thanks for the help!

2024-01-18 20:24 UTC, AndrewLam288 approved these changes, later dismissed

2024-01-19 20:17 UTC, elyjohnson approved these changes, later dismissed

2024-01-19 21:23 UTC, NicMcPhee requested changes
There are a couple of minor spacing issues that you should probably fix.

Other than that it look great!

2024-01-19 21:23 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> + }
It looks like this close brace isn't indented correctly and should be one more space to the right?

2024-01-19 21:23 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
I probably wouldn't have this blank line here.

2024-01-19 21:23 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> + }
I would also typically put a blank line between function definitions, so add a blank line after this curly brace.

2024-01-19 21:27 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
>    private String KenSaysHello() {
```suggestion
  private String malenaSaysHello() {
    return "Malena says 'Hi!'\n";
  }
  
  private String KenSaysHello() {
```

2024-01-19 21:28 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
>    }
We typically wouldn't want a blank line like this at the end of a function definition.

```suggestion
  private String patSaysHello() {
    return "Pat says 'Hello to everyone!'\n";
  }
```

2024-01-19 21:31 UTC, NicMcPhee submitted a review, later dismissed

2024-01-20 23:00 UTC, NicMcPhee submitted a review, later dismissed

2024-01-21 00:48 UTC, KenBroden approved these changes, later dismissed
Looks good

2024-01-21 16:20 UTC, KenBroden approved these changes

2024-01-21 19:12 UTC, LinneaMay approved these changes
looks good!

2024-01-21 19:14 UTC, merged