Added greeting from Ethan
UMM-CSci-3601-S24/intro-to-git-everyone pull request #9
Opened 2024-01-18 20:13 UTC by ethangraybar

I added a greeting for myself.

2024-01-18 20:22 UTC, alijawosti approved these changes, later dismissed

2024-01-18 20:22 UTC, TyBeas approved these changes, later dismissed

2024-01-19 21:35 UTC, NicMcPhee requested changes
You really should remove the file `intro-to-git-everyone/user_info/Ethan.md` before you merge this in.

2024-01-19 21:35 UTC, NicMcPhee commented on intro-to-git-everyone/user_info/Ethan.md
> +# Ethan Graybar
This file shouldn't be here. I think this is from when you had checked out a copy of the repository inside another copy of the repository. We definitely don't want to commit that. So I would remove this file before merging in this pull request.

2024-01-20 23:02 UTC, NicMcPhee requested changes

2024-01-20 23:02 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
>      builder.append(elySaysHello());
You've got your alphabetization wrong here, which is why your tests are failing. You want to be after Ely.

```suggestion
    builder.append(andreasSaysHello());
    builder.append(elySaysHello());
    builder.append(ethanSaysHello());
```

2024-01-21 17:52 UTC, KenBroden commented on user_info/Ethan.md
> +- My github homepage is [github.com/ethangraybar](https://github.com/kklamberty/).
You left in KK's github link here

2024-01-22 18:49 UTC, NicMcPhee approved these changes

2024-01-22 18:50 UTC, jmahoney5 approved these changes
Looks Good

2024-01-22 18:52 UTC, merged